const KEY='press-step-user-v1';
const lessons={5:[['뉴스란 무엇일까?','뉴스의 뜻과 특징을 알아봐요.'],['사실과 의견 구별하기','사실과 의견을 찾아 구별해요.'],['뉴스의 육하원칙','누가, 언제, 어디서, 무엇을, 어떻게, 왜를 살펴봐요.'],['뉴스의 제목 만들기','핵심이 잘 드러나는 제목을 지어봐요.'],['인터뷰 질문 만들기','좋은 질문으로 생각을 끌어내요.'],['인터뷰 기사 읽기','인터뷰 속 정보를 찾아 정리해요.'],['사진과 영상의 역할','사진과 영상이 전하는 메시지를 생각해요.'],['미디어 속 정보 확인하기','출처를 확인하고 꼼꼼히 살펴봐요.'],['나만의 기사 쓰기','알맞은 순서로 기사를 완성해요.'],['우리 반 작은 언론사','배운 내용을 모아 기자가 되어봐요.']],6:[['미디어와 나','미디어를 사용하는 나의 모습을 돌아봐요.'],['정보의 출처 찾기','정보가 어디에서 왔는지 확인해요.'],['팩트체크 첫걸음','주장의 사실 여부를 점검해요.'],['가짜 뉴스 알아보기','그럴듯한 정보 속 단서를 찾아요.'],['알고리즘 이해하기','내게 보이는 콘텐츠가 정해지는 원리를 알아봐요.'],['미디어 편향 살펴보기','하나의 사건을 여러 관점에서 바라봐요.'],['저작권과 초상권','만들고 나눌 때 지켜야 할 약속을 배워요.'],['디지털 시민의 약속','책임 있는 미디어 이용을 실천해요.'],['좋은 기사 기획하기','누구에게 어떤 이야기를 전할지 기획해요.'],['나의 기자증 프로젝트','나만의 미디어 실천 약속을 완성해요.']]};
const ranks=[['씨앗 기자',0,'🌱'],['새싹 기자',2,'🌿'],['탐험 기자',4,'🗺️'],['알찬 기자',6,'📰'],['빛나는 기자',8,'⭐'],['우리 반 기자장',10,'🎖️']];
let state=JSON.parse(localStorage.getItem(KEY)||'null'); let currentView='home'; let selectedGrade=state?.grade||5; let selectedLesson=null;
const $=s=>document.querySelector(s); const app=$('#app');
function save(){localStorage.setItem(KEY,JSON.stringify(state))} function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function countForGrade(){return state.records.filter(x=>x.grade===selectedGrade).length} function levelForCount(count){return Math.min(5,Math.floor(count/2)+1)} function rank(){let n=countForGrade(); return [...ranks].reverse().find(r=>n>=r[1])||ranks[0]} function next(){return ranks.find(r=>r[1]>countForGrade())} function isCertified(){return countForGrade()>=10} function certificateCard(){return `<div class="certificate"><span class="certificate-kicker">PRESS · MEDIA LITERACY PROGRAM</span><div class="certificate-seal">PRESS<br>인증</div><h2>PRESS 기자증</h2><div class="certificate-name">${esc(state.nickname)} 기자</div><div class="certificate-meta"><span>${selectedGrade}학년 워크북 10차시 완주</span><span>LV.5</span></div></div>`}
function shell(content){app.innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand" onclick="go('home')"><div class="brand-mark">P</div><div><div class="brand-name">PRESS 한걸음</div><div class="brand-sub">읽고, 생각하고, 기록하는 작은 기자</div></div></div><div class="header-user"><span>${esc(state.nickname)} 기자</span><button class="small-btn" onclick="logout()">나가기</button></div></header><main class="page">${content}</main><nav class="bottom-nav"><button class="nav-btn ${currentView==='home'?'active':''}" onclick="go('home')">⌂ 홈</button><button class="nav-btn ${currentView==='record'?'active':''}" onclick="go('record')">✎ 기록하기</button><button class="nav-btn ${currentView==='growth'?'active':''}" onclick="go('growth')">✦ 성장 현황</button></nav><div id="modal" class="modal-backdrop"></div><div id="toast" class="toast"></div></div>`}
function home(){currentView='home';selectedGrade=state.grade||selectedGrade;let r=rank(),n=next(),count=countForGrade(),pct=n?Math.round(count/(n[1])*100):100; shell(`<section class="hero"><div><p class="eyebrow">${selectedGrade}학년 워크북</p><h1>${esc(state.nickname)} 기자, 안녕하세요!</h1><p>오늘 공부한 차시를 기록하고<br>나만의 기자증을 채워 가 보세요.</p><button class="primary" onclick="go('record')" style="margin-top:20px">기록 시작하기 →</button></div><div class="hero-art">${r[2]}</div></section><div class="section-head"><div><h2>${selectedGrade}학년 기자 활동</h2><p>10차시를 모두 완료하면 최종 LV.5 기자증을 받아요.</p></div></div><div class="grid"><div class="stat-card"><span class="emoji">📚</span><div class="label">완료한 차시</div><div class="value">${count}<small>/ 10</small></div></div><div class="stat-card"><span class="emoji">🏷️</span><div class="label">받은 스티커</div><div class="value">${count}개</div></div><div class="stat-card"><span class="emoji">🎖️</span><div class="label">현재 레벨</div><div class="value">LV.${Math.min(5,Math.floor(count/2)+1)}</div></div><div class="stat-card"><span class="emoji">✦</span><div class="label">현재 기자증</div><div class="value" style="font-size:22px">${r[0]}</div></div></div><div class="progress-card"><div class="growth-icon">${r[2]}</div><div style="flex:1"><h2>${r[0]}</h2><p>${n?`${n[1]-count}차시 더 완료하면 ${n[0]}로 레벨업해요.`:'10차시 완주! 최종 LV.5 기자증이 완성되었어요.'}</p><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><div class="progress-meta"><span>현재 ${count}차시</span><span>${n?'다음 레벨까지 '+(n[1]-count)+'차시':'완료!'}</span></div></div></div><div class="section-head"><div><h2>${selectedGrade}학년 워크북 10차시</h2><p>선택한 학년의 차시만 표시됩니다.</p></div></div><div class="lesson-grid">${lessons[selectedGrade].map((l,i)=>lessonCard(l,i)).join('')}</div>`)}
function lessonCard(l,i){let done=state.records.some(x=>x.grade===selectedGrade&&x.lesson===i);return `<div class="lesson-card ${done?'done':''}" onclick="startLesson(${selectedGrade},${i})"><span class="lesson-number">${selectedGrade}학년 · ${i+1}차시</span>${done?'<span class="done-mark">✓</span>':''}<h3>${esc(l[0])}</h3><p>${esc(l[1])}</p></div>`}
function record(){currentView='record';shell(`<section class="section-head"><div><p class="eyebrow">${selectedGrade}학년 워크북</p><h2>학습 기록 남기기</h2><p>${selectedGrade}학년 10차시 중 완료한 차시를 선택하고, 오늘의 배움과 소감을 적어 주세요.</p></div></section><div class="form-card"><label for="lesson">${selectedGrade}학년 차시</label><select id="lesson">${lessons[selectedGrade].map((l,i)=>`<option value="${selectedGrade}-${i}">${i+1}차시 · ${l[0]}</option>`).join('')}</select><label for="learn">오늘 배운 내용 <span class="badge">필수</span></label><textarea id="learn" placeholder="새롭게 알게 된 내용을 적어 보세요."></textarea><label for="feel">오늘의 소감 <span class="badge">필수</span></label><textarea id="feel" placeholder="공부하며 느낀 점이나 실천하고 싶은 점을 적어 보세요."></textarea><div id="record-msg" class="message"></div><div class="form-actions"><button class="secondary" onclick="go('home')">돌아가기</button><button class="primary" onclick="completeLesson()">기록하고 스티커 받기</button></div></div>`)}
function syncLessonOptions(){return}
function growth(){currentView='growth';let r=rank(),n=next(),records=state.records.filter(x=>x.grade===selectedGrade),count=records.length;shell(`<section class="section-head"><div><p class="eyebrow">${selectedGrade}학년 성장 기록</p><h2>성장 현황</h2><p>한 차시씩 모인 기록이 나만의 기자증이 되었어요.</p></div></section><div class="progress-card"><div class="growth-icon">${r[2]}</div><div><h2>${r[0]}</h2><p>LV.${Math.min(5,Math.floor(count/2)+1)} · 스티커 ${count}개</p><p>${n?`다음 기자증까지 ${n[1]-count}차시`:'10차시 완주! 최종 LV.5 기자증이 완성되었어요.'}</p></div></div>${isCertified()?certificateCard():''}<div class="section-head"><div><h2>${selectedGrade}학년 학습 기록 <small>(${count})</small></h2></div></div><div class="record-list">${records.length?records.slice().reverse().map((x,i)=>`<div class="record-item" onclick="showDetail(${state.records.indexOf(x)})"><div class="record-top"><h3>${esc(x.lessonTitle)}</h3><span class="badge">스티커 +1</span></div><div class="record-meta">${x.grade}학년 ${x.lesson+1}차시 · ${x.date}</div></div>`).join(''):'<div class="empty">아직 기록이 없어요.<br
>첫 번째 차시를 완료해 보세요!</div>'}</div>`)}
function startLesson(g,i){selectedGrade=g;selectedLesson=i;record();$('#lesson').value=`${g}-${i}`;$('#lesson').disabled=true}
function completeLesson(){let val=$('#lesson').value.split('-'),g=Number(val[0]),i=Number(val[1]),learn=$('#learn').value.trim(),feel=$('#feel').value.trim(); if(!learn||!feel){$('#record-msg').textContent='오늘 배운 내용과 소감을 모두 적어 주세요.';return} if(state.records.some(x=>x.grade===g&&x.lesson===i)){showToast('이미 완료한 차시예요. 다른 차시를 선택해 주세요.');return} let before=state.records.filter(x=>x.grade===g).length,oldLevel=levelForCount(before);state.records.push({grade:g,lesson:i,lessonTitle:lessons[g][i][0],lessonDesc:lessons[g][i][1],learn,feel,date:new Date().toLocaleDateString('ko-KR'),sticker:true});state.stickers++;let newLevel=levelForCount(before+1);state.celebration=newLevel>oldLevel?{level:newLevel,grade:g}:null;save();selectedGrade=g;completeScreen()}
function confetti(){let colors=['#3b83c6','#f59b52','#70b66b','#f3c84b','#e87878','#8b75ca'];return Array.from({length:28},(_,i)=>`<i class="confetti" style="left:${(i*37)%100}%;background:${colors[i%colors.length]};animation-delay:${(i%8)*.08}s;transform:rotate(${i*19}deg)"></i>`).join('')}
function completeScreen(){currentView='home';let certified=isCertified(),celebration=state.celebration;state.celebration=null;save();shell(`<div class="form-card" style="text-align:center;margin-top:70px">${celebration?`<div class="celebration">${confetti()}<div style="font-size:58px">🎉</div><p class="eyebrow">업적 달성!</p><h2>LV.${celebration.level} 레벨업!</h2><p>${celebration.level===5?'10차시 완주! 최종 PRESS 기자증이 발급되었어요.':'새 업적을 달성했어요. 정말 멋진 기자예요!'}</p></div>`:''}<div style="font-size:76px">${certified?'🏅':'🎖️'}</div><p class="eyebrow">${certified?'최종 단계 완료!':'차시 완료!'}</p><h1 style="font:35px Jua;color:var(--navy);margin:10px 0">${certified?'PRESS 기자증 발급 완료!':'스티커 1개 획득!'}</h1><p>${certified?`${esc(state.nickname)} 기자의 이름으로 ${selectedGrade}학년 PRESS 기자증이 발급되었어요.`:'기록이 안전하게 저장되었어요.\n꾸준히 기록하면 기자증이 더 빛나요.'}</p>${certified?certificateCard():''}<div class="form-actions"><button class="secondary" onclick="go('record')">다음 차시 기록하기</button><button class="primary" onclick="go('growth')">성장 현황 보기</button></div></div>`)}
function showDetail(idx){let x=state.records[idx];$('#modal').innerHTML=`<div class="modal"><div style="display:flex;justify-content:space-between"><h2>${esc(x.lessonTitle)}</h2><button class="small-btn" onclick="closeModal()">닫기 ✕</button></div><div class="detail-line"><strong>학습 차시</strong>${x.grade}학년 ${x.lesson+1}차시 · ${x.date}</div><div class="detail-line"><strong>오늘 배운 내용</strong>${esc(x.learn)}</div><div class="detail-line"><strong>오늘의 소감</strong>${esc(x.feel)}</div><div class="detail-line"><strong>보상</strong>스티커 1개 획득 ✓</div></div>`;$('#modal').classList.add('open')}
function closeModal(){$('#modal').classList.remove('open')} function showToast(t){let e=$('#toast');e.textContent=t;e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}
function setGrade(g){selectedGrade=g;state.grade=g;save();home()} function go(v){v==='home'?home():v==='record'?record():growth()} function logout(){state=null;login()}
function login(){let saved=JSON.parse(localStorage.getItem(KEY)||'null'),hasSaved=!!(saved&&saved.nickname);app.innerHTML=`<main class="login-wrap"><section class="login-card"><div class="brand-mark">P</div><h1>${hasSaved?'PRESS 한걸음 불러오기':'PRESS 한걸음'}</h1><p>${hasSaved?'저장된 기자 기록을 불러와 계속 이어가세요.':'교실 속 작은 언론사에서<br>나만의 기자증을 만들어 보세요.'}</p><label for="nickname" style="text-align:left">닉네임</label><input id="nickname" placeholder="예: 반짝이는 민지 기자" maxlength="12"><label for="grade-choice" style="text-align:left">학년 선택</label><select id="grade-choice"><option value="5">5학년 워크북 · 10차시</option><option value="6">6학년 워크북 · 10차시</option></select><label for="pin" style="text-align:left">4자리 숫자 비밀번호</label><input id="pin" type="password" inputmode="numeric" maxlength="4" placeholder="숫자 4자리"><div id="login-msg" class="message" style="text-align:left"></div><button class="primary" style="width:100%;margin-top:20px" onclick="loginStart()">${hasSaved?'기록 불러오기 →':'내 기자 기록 시작하기 →'}</button><p style="font-size:12px;margin-top:18px">이 기록은 현재 기기에만 저장됩니다.</p></section></main>`;if(hasSaved){$('#grade-choice').value=String(saved.grade||5)}}
function loginStart(){let n=$('#nickname').value.trim(),p=$('#pin').value.trim(),g=Number($('#grade-choice').value),m=$('#login-msg'),saved=JSON.parse(localStorage.getItem(KEY)||'null');if(!n){m.textContent='닉네임을 입력해 주세요.';return}if(!/^\d{4}$/.test(p)){m.textContent='비밀번호는 숫자 4자리로 입력해 주세요.';return}if(saved&&saved.nickname){if(n!==saved.nickname||p!==saved.pin||g!==(saved.grade||5)){m.textContent='닉네임, 학년 또는 비밀번호를 확인해 주세요.';return}state=saved;state.records=state.records||[];state.stickers=state.stickers||0;selectedGrade=state.grade||5;save();home();return}state={nickname:n,pin:p,grade:g,stickers:0,records:[]};selectedGrade=g;save();home()}
if(state&&state.nickname){state.grade=state.grade||5;selectedGrade=state.grade;state.records=state.records||[];state.stickers=state.stickers||0;save();home()}else login();

